apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: visualization-kube-public
  namespace: argocd
spec:
  destination:
    namespace: kube-public
    server: https://kubernetes.default.svc
  project: default
  source:
    path: templates/visualization
    repoURL: https://github.com/ms-03/cluster-api-test
    targetRevision: HEAD
  syncPolicy:
    automated: {}
