apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: visualization-argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: templates/visualization
    repoURL: https://github.com/ms-03/cluster-api-test
    targetRevision: HEAD
  syncPolicy:
    automated: {}
